### PR TITLE
Updates for syntax up to CMake 3.14.0

### PR DESCRIPTION
**Pull request by madscientist**
I based this on the head of repo MarkaPola/cmake-font-lock then added extra updates for CMake 3.14.0.

It would be nice to have a version with these changes available in ELPA.

Thanks!

### CODE REVIEW

**Comment by Lindydancer** [comment]
Hi!

It's been on my todo list for some time to update this package for the
latest CMake, but I have had difficulties finding time for it...

Before I accept your pull request, I would like to ask you a straight
forward question. Would you considering placing your changes under Public
Domain, and ask MarkaPola to do the same? The reason I ask is that I would
like to keep the list of copyright holders as short as possible, in case I
get the opportunity to include the package in the Emacs distribution. (I
already have three packages in the distribution and one more in the
pipeline for Emacs 27.)

Thanks for submitting the pull request!

    -- Anders

**Comment by madscientist** [comment]
Sure; I hereby disclaim all copyright on changes in pull #7 that are authored by me and place them into the public domain.

@MarkaPola I based my changes on the master HEAD of your fork repo MarkaPola/cmake-font-lock : would you be willing to put the changes you made for CMake 3.11 and 3.12 into the public domain?

**Comment by MarkaPola** [comment]
Sure, you can put my changes (commits 1375b07 and  b38675f) in the public domain.

**Comment by Lindydancer** [comment]
Hi!

I just pushed an updated version with your changes (and some minor stuff I
hadn't pushed before).

Big thanks to both of you!

Just a technical note -- I keep all my Emacs packages in subversion and
publish them on github using "git svn". Unfortunately, this breaks the
connection between the pull request commits and what is seen in the
published archive.

    -- Anders

**Comment by Lindydancer** [comment]
Apparently, I didn't close the 3.14 issue when it was fixed, so I'm doing it now.

**Pull request closed without merging**
